export enum AppMode {
  COMMAND = "command",
  PAGES = "pages",
  TRACKED = "tracked",
  TRACK_PICKER = "trackpicker",
  COPY_PAGES = "copypages",
  COMPARE = "compare",
  STATUS = "status",
  SYNC = "sync",
  CONFIG = "config",
  NAVIGATION = "navigation",
  USERS = "users",
  GROUPS = "groups",
  EXPORTS = "exports",
  SETUP = "setup",
  HELP = "help",
  THEME = "theme",
}
